/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CmpAvatar {
    }
    interface MyComponent {
    }
}
declare global {
    interface HTMLCmpAvatarElement extends Components.CmpAvatar, HTMLStencilElement {
    }
    var HTMLCmpAvatarElement: {
        prototype: HTMLCmpAvatarElement;
        new (): HTMLCmpAvatarElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "cmp-avatar": HTMLCmpAvatarElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface CmpAvatar {
    }
    interface MyComponent {
    }
    interface IntrinsicElements {
        "cmp-avatar": CmpAvatar;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cmp-avatar": LocalJSX.CmpAvatar & JSXBase.HTMLAttributes<HTMLCmpAvatarElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
